### ISSUE TITLE
Suggestion. use `use-immer` module for better state update. 

### ISSUE THREAD

**Issue by mt-sette** [RabbitHole26/react-state-management-system#4]
Read first the [react doc](https://react.dev/learn/extracting-state-logic-into-a-reducer#writing-concise-reducers-with-immer) and the package recommendation, [useImmerReducer](https://github.com/immerjs/use-immer#useimmerreducer). 

```js
// App.jsx
import { useImmerReducer } from 'use-immer';

function App() {
    // * useReducer hook is declared on the 'App.jsx' level
    const [state, dispatch] = useImmerReducer(reducer, initialState);
    
  // rest of the code
 }
```
Update the reducer

```js
// counter-reducer.js
const counterReducer = (state, action) => {
    let updatedState = null;

    switch (action.type) {
        case 'INCREMENT_COUNTER':
            state.counter.count++;
            localStorage.setItem('count', state.counter.count);
            
            // also works without the keyword 'void'
            return void state;
            
            // rest of the code
 }
```

I would be simpler if you didn't use localStorage, but hey :smile:

**Comment by RabbitHole26** [comment]
Mutating the values in the immer draft object directly simplifies the code a lot, that was a great suggestion. Thanks.

Regarding the localStorage, I will comment it out for the time being. Since this demo focuses on the state management only it is adding unnecessary complexity.
